
vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet
    - formulahendry.auto-close-tag
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags